### ISSUE TITLE
server game bug

### ISSUE THREAD

**Issue by TheMi1k** [pog5/mc-leashplayers#7]
My version is 1.20.1. In the local game, I can lead bot player, and the lead is displayed correctly. In the server game, I can lead other players, but the lead isn't displayed.

**Comment by pog5** [comment]
It's a visual bug due to how leashes are created, since i dont want to keep a constant map/list of all leashes since that would be somewhat performance intensive this was the easiest way to implement it
if you know how to optimize it, please feel free to make a PR and i will merge it :)
